name: Sync Kernel Source and Build Upload

on:
  workflow_dispatch:

jobs:
  sync_kernel_source_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Repo Tool
      run: |
        sudo apt-get update
        sudo apt-get install -y repo
        
    - name: Get kernel_manifest.xml from Repository Folder
      run: |
        cp kernel_manifest/kernel_manifest.xml kernel_manifest.xml
        # 例如，如果kernel_manifest.xml在仓库的kernels文件夹下，可替换为：
        # cp kernels/kernel_manifest.xml kernel_manifest.xml

    - name: Sync Kernel Source
      run: |
        repo init -u https://android.googlesource.com/kernel/manifest
        mv kernel_manifest.xml .repo/manifests
        repo init -m kernel_manifest.xml
        repo sync -j42

    # - name: Set Build Environment Variables
    #   run: |
    #     export LTO=thin
    #     export BUILD_CONFIG=common/build.config.gki.aarch64

    # - name: Build Kernel
    #   run: |
    #     cd build
    #     bash build.sh




    - name: Upload Entire Folder to Repository
      uses: actions/upload-artifact@v3
      with:
        name: kernel_upload_folder
        path: /home/runner/work/android-common-kernel-5.10/android-common-kernel-5.10
