name: Sync Kernel Source and Build Upload

on:
  workflow_dispatch:

jobs:
  sync_kernel_source_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Repo Tool
      run: |
        sudo apt-get update
        sudo apt-get install -y repo
        
    - name: Get kernel_manifest.xml from Repository Folder
      run: |
        cp kernel_manifest/kernel_manifest.xml kernel_manifest.xml
        # 例如，如果kernel_manifest.xml在仓库的kernels文件夹下，可替换为：
        # cp kernels/kernel_manifest.xml kernel_manifest.xml

    - name: Sync Kernel Source
      run: |
        repo init -u https://android.googlesource.com/kernel/manifest
        mv kernel_manifest.xml .repo/manifests
        repo init -m kernel_manifest.xml
        repo sync

    # - name: Set Build Environment Variables
    #   run: |
    #     export LTO=thin
    #     export BUILD_CONFIG=common/build.config.gki.aarch64

    # - name: Build Kernel
    #   run: |
    #     cd build
    #     bash build.sh

    - name: Create Upload Folder
      run: |
        mkdir kernel_upload_folder

    - name: Move Files to Upload Folder
      run: |
        cp -r./* kernel_upload_folder/  # 将当前目录下的所有文件和子目录复制到新建的文件夹中
        # 这里假设你想要排除一些不必要的文件或目录，可以根据实际情况添加相应的排除条件
        # 例如，如果要排除.git目录，可以使用：cp -r --exclude=.git./* kernel_upload_folder/

    - name: Upload Entire Folder to Repository
      uses: actions/upload-artifact@v3
      with:
        name: kernel_upload_folder
        path: kernel_upload_folder
